### ISSUE TITLE
can you provide More complex example?

### ISSUE THREAD

**Issue by liu-xinhui** [pyricau/fragnums#10]
this framwork is so novel,but I donot kown where to wirte network code,can you provide More complex example?

**Comment by NightlyNexus** [comment]
https://github.com/pyricau/fragnums#why-should-i-use-fragnums

**Comment by capezzbr** [comment]
Also

> We suggest you start using a smaller font size in your IDE.

please

**Comment by frostymarvelous** [comment]
Can Enums actually scale? I am thinking of porting my App, but I have a lot of code in each Activity/Fragment. Just thinking if Enums can actually scale to meet that.

I might just have to use classes with the same concept here. Awesome but we still need a complex example.

**Comment by pyricau** [comment]
:joy:
