### ISSUE TITLE
more update 

### ISSUE THREAD

**Issue by microcian** [pyricau/fragnums#14]
Awesome library and i want to know more about if i have some adapter and recycler view or also some click listener of adapter so everything related to that view should be in the following code ??
onBind ?

as you write some piece of code 
T_SHIRT(R.layout.tshirt, R.string.tshirt_title) {
    @Override protected void onBind() {
      findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
        @Override public void onClick(View view) {
          Intent intent = new Intent(ACTION_VIEW, Uri.parse("https://teespring.com/enumsmatter"));
          view.getContext().startActivity(intent);
        }
      });
    }
  };

**Comment by pyricau** [comment]
nope!

**Comment by microcian** [comment]
then should be the mechanism for that

**Comment by pyricau** [comment]
https://github.com/pyricau/fragnums#is-this-serious
