### ISSUE TITLE
Find an alternative to bronum

### ISSUE THREAD

**Issue by djensen47** [pyricau/fragnums#4]
Try a more inclusive term like:
- friend + enum = _frinum_
- hug + enum = _hugum_ or _hugnum_

… uh, that's all I got (and it's not great) but I'm sure you get the idea.

**Comment by pyricau** [comment]
That's the whole point of sarcasm. Making fun of #perfmatters but also making fun of the tshirt thing, and pointing out that #enumsmatter is a little bit of a cult thing as well.

**Comment by djensen47** [comment]
BTW, thanks for being willing to have a conversation on this.

The tech industry has a problem with inclusion and diversity. Even joking around using satire can hurt efforts to turn things around. Maybe the intent of the sarcasm is to criticize "bro" culture but it's a slippery slope to being misunderstood and ultimately defeating the purpose of the sarcasm.

Also, some people don't get sarcasm or are slower picking up on it. Maybe a good comedy writer could layer in a message that is both sarcastic but clearly critical of non-inclusiveness but I don't think that  happened here.

Maybe the bug I should've file is that the "bronum" sarcasm is broken, it can be misinterpreted. And if you put it on a t-shirt then it's definitely broken. An "inside" (Android devs) joke will not be understood on the outside and will just make the community seem non-inclusive.

**Comment by djensen47** [comment]
:+1:
