### ISSUE TITLE
Too much awesomeness in this library

### ISSUE THREAD

**Issue by Aracem** [pyricau/fragnums#8]
The trolling level in the library I think is correct but your awesomeness surpass the maximun level.

I dont think is important enought to fix this "bug", but... dude, I have to tell you!

![applause](https://cloud.githubusercontent.com/assets/2283594/11166437/8b3a9d1a-8b33-11e5-9f53-0b9ea7a3cf1b.gif)

**Comment by rallat** [comment]
:+1:
